"""Generate ``docs/reference/*.md`` from the code, so the two can never drift.

FOR: turning the tables a consumer would otherwise have to open a Python
REPL, a running unit, or a vendor package to find -- the route table, the
shipped profiles, the fault catalogue, the environment variables, the
control plane, the CLI's own ``--help`` -- into committed markdown pages a
browser (or a search index) can read. Every page is produced from the exact
object the corresponding piece of the runtime already publishes:
``vendorfake.registry.routes`` (the same rows ``GET /__unit/routes``
serves), ``vendorfake.registry.available_profiles`` (the same documents
``load_profile`` validates), ``vendorfake.core.chaos.faults.FAULT_PARAM_KEYS``
/ ``FAULT_DESCRIPTIONS`` and ``vendorfake.core.chaos.rules.BUILTIN_FAULTS``
(what ``GET /__unit/chaos`` lists), ``vendorfake.core.config.profile.ENV_TABLE``
(what ``load_profile`` reads), the OpenAPI document
``vendorfake.core.control.openapi.document_for_unit`` builds (filtered to
``/__unit/*``), and ``vendorfake.cli``'s own ``argparse`` parser
(``--help``, verbatim). There is no second, hand-maintained copy of any of
these anywhere in this file.

INVARIANT: **generated output is committed, and staleness is a build
failure.** This mirrors the pattern ``konyklabs/.github``'s ``arch/`` uses
for ``arch/generated/VIEWS.md``: a human reads the committed page on GitHub
with no tooling, and ``tools/self-test.sh`` re-runs this generator and fails
if the working tree then differs -- so a route added to a vendor's surface
without re-running this script is a red self-test, not a page that quietly
falls behind the code it describes.

INVARIANT: **one interpreter, one width, writes ``cli.md``.** Every other page is a
function of the code alone, but ``cli.md`` is ``argparse``'s own ``--help``
text, and ``argparse`` lays that text out differently across CPython minor
versions (3.11 and 3.13 disagree on the column a subcommand's help starts
in, so the same parser yields two byte-different pages). The page is
therefore generated under the interpreter ``CLI_PAGE_INTERPRETER`` names and left
untouched -- with a note on stderr -- under any other, so a self-test on the
``requires-python`` floor still checks the seven code-derived pages without
failing on a layout difference no code change caused. The wrap width is
forced to 80 columns for the same reason: ``argparse`` otherwise reads the
contributor's terminal width, and a 120-column window would rewrap the page.

INVARIANT: **idempotent.** Running this script twice in a row with no code
change between the two runs produces byte-identical output the second time.
Every source this module reads is already deterministic (a route table, a
profile document, a fixed-order fault catalogue, ``ENV_TABLE``'s declared
order); this module adds no sorting of its own beyond what is needed to make
a table's row order a property of the source rather than of dict iteration.

Every generated file opens with an HTML-comment banner naming this script
and the symbol it was generated from -- the "generated, and by what" the
spec asks for -- so a reader who lands on the page from a search engine, not
from the docs nav, still knows not to hand-edit it.
"""

from __future__ import annotations

import argparse
import os
import sys
from collections.abc import Iterable, Sequence
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
REFERENCE_DIR = REPO_ROOT / "docs" / "reference"
GENERATOR = "tools/gen_reference.py"


# ---------------------------------------------------------------------------
# Small markdown helpers. No templating dependency earns its place for eight
# files this shaped -- a banner, a heading, and a table.
# ---------------------------------------------------------------------------


def _cell(value: object) -> str:
    """One table cell: ``None`` and ``()`` render empty, a pipe cannot break
    the row, and a newline (a docstring-derived summary, occasionally) cannot
    either."""
    if value is None or value == "":
        return ""
    text = ", ".join(value) if isinstance(value, (tuple, list)) else str(value)
    return text.replace("|", "\\|").replace("\n", " ").strip()


def _table(headers: Sequence[str], rows: Iterable[Sequence[object]]) -> str:
    lines = [
        "| " + " | ".join(headers) + " |",
        "| " + " | ".join("---" for _ in headers) + " |",
    ]
    for row in rows:
        lines.append("| " + " | ".join(_cell(value) for value in row) + " |")
    return "\n".join(lines) + "\n"


def _banner(source: str) -> str:
    return f"<!-- GENERATED by `{GENERATOR}` from {source}. Do not hand-edit; re-run `uv run python {GENERATOR}`. -->\n"


def _write(filename: str, *, source: str, title: str, intro: str, body: str) -> None:
    text = f"{_banner(source)}\n# {title}\n\n{intro.strip()}\n\n{body.strip()}\n"
    (REFERENCE_DIR / filename).write_text(text, encoding="utf-8")


# ---------------------------------------------------------------------------
# routes-<vendor>.md
# ---------------------------------------------------------------------------


def _routes_page(vendor: str) -> None:
    from vendorfake.registry import routes as list_routes

    rows = [row for row in list_routes(vendor) if not row.internal]
    _write(
        f"routes-{vendor}.md",
        source=f"`vendorfake.registry.routes({vendor!r})`",
        title=f"{vendor.capitalize()} routes",
        intro=(
            f"Every route {vendor}'s surface serves -- vendor-facing only. "
            "The `/__unit/*` control plane is the same for every vendor; see "
            "[Control plane](control-plane.md)."
        ),
        body=_table(
            ("Method", "Path", "Operation", "Capability", "Summary"),
            ((row.method, f"`{row.path}`", row.operation_id, row.capability, row.summary) for row in rows),
        ),
    )


# ---------------------------------------------------------------------------
# profiles.md
# ---------------------------------------------------------------------------


def _profiles_page(vendors: Sequence[str]) -> None:
    from vendorfake.registry import available_profiles

    sections = []
    for vendor in vendors:
        rows = [
            (f"`{profile.name}`", profile.capabilities, profile.seed, profile.summary)
            for profile in available_profiles(vendor)
        ]
        sections.append(f"## {vendor.capitalize()}\n\n" + _table(("Profile", "Capabilities", "Seed", "Summary"), rows))
    _write(
        "profiles.md",
        source="`vendorfake.registry.available_profiles`",
        title="Profiles",
        intro="Every profile every vendor ships.",
        body="\n\n".join(sections),
    )


# ---------------------------------------------------------------------------
# faults.md
# ---------------------------------------------------------------------------


def _faults_page() -> None:
    from vendorfake.core.chaos.faults import FAULT_DESCRIPTIONS, FAULT_PARAM_KEYS
    from vendorfake.core.chaos.rules import BUILTIN_FAULTS

    scope_of = {spec.name: spec.scope for spec in BUILTIN_FAULTS}
    provenance_of = {spec.name: spec.provenance for spec in BUILTIN_FAULTS}
    phase_of = {spec.name: spec.phase for spec in BUILTIN_FAULTS}
    rows = [
        (
            f"`{name}`",
            scope_of.get(name, ""),
            provenance_of.get(name, ""),
            phase_of.get(name, ""),
            keys,
            FAULT_DESCRIPTIONS.get(name, ""),
        )
        for name, keys in FAULT_PARAM_KEYS.items()
    ]
    _write(
        "faults.md",
        source=(
            "`vendorfake.core.chaos.faults.FAULT_PARAM_KEYS` / `FAULT_DESCRIPTIONS`, "
            "`vendorfake.core.chaos.rules.BUILTIN_FAULTS` (scope, provenance, phase)"
        ),
        title="Faults",
        intro=(
            "Every built-in fault. `provenance: vendor` reproduces a failure mode "
            "the vendor documents; `provenance: transport` is a transport-level "
            "failure mode no vendor documents. `phase: request` fires instead of "
            "the handler, so nothing is committed; `phase: response` fires on the "
            "answer *after* the handler committed, so a retry does not start "
            "clean; `phase: delivery` is a webhook delivery. See "
            "[Chaos](../concepts/chaos.md) and "
            "[Provenance labels](../concepts/chaos.md#provenance)."
        ),
        body=_table(("Fault", "Scope", "Provenance", "Phase", "Params", "Description"), rows),
    )


# ---------------------------------------------------------------------------
# env.md
# ---------------------------------------------------------------------------


def _env_page() -> None:
    from vendorfake.core.config.profile import ENV_TABLE

    rows = [
        (
            f"`{var.name}{'<suffix>' if var.is_prefix else ''}`",
            var.applies_to,
            var.summary,
        )
        for var in ENV_TABLE
    ]
    _write(
        "env.md",
        source="`vendorfake.core.config.profile.ENV_TABLE`",
        title="Environment variables",
        intro="Every environment variable `load_profile` reads.",
        body=_table(("Variable", "Applies to", "Summary"), rows),
    )


# ---------------------------------------------------------------------------
# control-plane.md
# ---------------------------------------------------------------------------


def _control_plane_page(vendor: str) -> None:
    from vendorfake.core.control.plane import CONTROL_PREFIX
    from vendorfake.registry import create_unit

    unit = create_unit(vendor=vendor)
    try:
        from vendorfake.core.control.openapi import document_for_unit

        document = document_for_unit(unit, include_internal=True)
    finally:
        unit.stop()

    rows = []
    for path, item in document["paths"].items():
        if not path.startswith(CONTROL_PREFIX):
            continue
        for method, op in item.items():
            rows.append((method.upper(), f"`{path}`", op.get("operationId"), op.get("summary")))

    _write(
        "control-plane.md",
        source="`vendorfake.core.control.openapi.document_for_unit(unit, include_internal=True)`",
        title="Control plane",
        intro=(
            f"Every `/__unit/*` route -- the operator's side channel for state, "
            f"time and observability -- identical for every vendor; generated "
            f"against a `{vendor}` unit, filtered to paths under `{CONTROL_PREFIX}`."
        ),
        body=_table(("Method", "Path", "Operation", "Summary"), rows),
    )


# ---------------------------------------------------------------------------
# cli.md
# ---------------------------------------------------------------------------


def _subcommands(parser: argparse.ArgumentParser) -> dict[str, argparse.ArgumentParser]:
    """Every subparser, in declaration order.

    Found by walking ``parser._actions`` for the one that ``isinstance``s as
    ``argparse._SubParsersAction`` -- mypy (unlike a plain attribute lookup
    through ``parser._subparsers``, which it can only see as
    ``_ArgumentGroup | None``) narrows an ``isinstance`` check to a type that
    actually declares ``.choices``, so this needs no ``# type: ignore``.
    """
    for action in parser._actions:
        if isinstance(action, argparse._SubParsersAction):
            return dict(action.choices)
    return {}


def _cli_page() -> None:
    from vendorfake.cli import _build_parser

    # ``argparse`` wraps help at ``shutil.get_terminal_size()``, which reads
    # ``$COLUMNS`` first and the controlling terminal second, so the page
    # would otherwise be a function of the contributor's window width, not of
    # the code. 80 is the non-TTY fallback CI already gets.
    os.environ["COLUMNS"] = "80"
    parser = _build_parser()
    sections = [f"## `vendorfake`\n\n```text\n{parser.format_help().rstrip()}\n```"]

    for name, subparser in _subcommands(parser).items():
        sections.append(f"## `vendorfake {name}`\n\n```text\n{subparser.format_help().rstrip()}\n```")

    _write(
        "cli.md",
        source="`vendorfake.cli._build_parser()` (`--help`, verbatim)",
        title="CLI",
        intro="Every subcommand's `--help`.",
        body="\n\n".join(sections),
    )


# The one interpreter whose ``argparse`` layout ``cli.md`` records. A constant
# here rather than a root ``.python-version`` file on purpose: ``uv run``
# honours that file ahead of the environment it finds, so it would silently
# re-resolve CI's ``requires-python`` floor row onto this version and the floor
# would stop being tested. This constant reaches nothing but this generator.
CLI_PAGE_INTERPRETER = "3.13"


def _pinned_version() -> str:
    return CLI_PAGE_INTERPRETER


def _is_pinned_interpreter() -> bool:
    return f"{sys.version_info[0]}.{sys.version_info[1]}" == _pinned_version()


# ---------------------------------------------------------------------------
# Entry point.
# ---------------------------------------------------------------------------


def main() -> int:
    from vendorfake.registry import available_vendors

    vendors = available_vendors()
    if not vendors:
        print(f"{GENERATOR}: no vendors installed; nothing to generate", file=sys.stderr)
        return 1

    REFERENCE_DIR.mkdir(parents=True, exist_ok=True)
    for vendor in vendors:
        _routes_page(vendor)
    _profiles_page(vendors)
    _faults_page()
    _env_page()
    _control_plane_page(vendors[0])
    if _is_pinned_interpreter():
        _cli_page()
    else:
        print(
            f"{GENERATOR}: cli.md left as committed -- argparse help layout differs across "
            f"interpreters; that page is generated under Python {_pinned_version()} "
            f"(CLI_PAGE_INTERPRETER), not {sys.version_info[0]}.{sys.version_info[1]}",
            file=sys.stderr,
        )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
